disabled_rules:
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - identifier_name
  - todo
  - function_parameter_count
  - unused_closure_parameter
  - nesting
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - large_tuple
  - implicit_getter

opt_in_rules:
  - redundant_nil_coalescing

excluded:
  - Carthage

force_cast:
  severity: warning
force_try:
  severity: warning

custom_rules:
  os_log_over_all:
    name: "Logging"
    regex: '(print|NSLog)\('
    message: "Project convention favours os_log for logging."
    match_kinds:
      - identifier
    severity: warning
