os: osx
osx_image: xcode11
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
before_script:
  - xcodebuild -version
  - carthage version
  - swiftlint version
  - "./bootstrap.sh"
script:
  - set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild test -scheme WWDC -project WWDC.xcodeproj | xcpretty -f `xcpretty-travis-formatter`
